services:
  #################################################################
  # NGINX SERVICE Requires a proxy like NPM or Traefik.
  #################################################################
  nginx:
    build: .docker/nginx
    restart: unless-stopped
    container_name: nginx
    ports:
      - 8081:80
    networks:
      - web #- Used with Traefik
      - tripwire
    labels:
      - "traefik.http.routers.nginx.rule=Host(`$TRDOMAIN`)" # Used with Traefik to set your host
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.enable=true" # Traefik is not enabled on all services by default
    volumes:
      - "./:/opt/app"

  #################################################################
  # PHP-FPM SERVICE
  #################################################################
  php-fpm:
    build: .docker/php-fpm
    container_name: php-fpm
    networks:
      - tripwire
    volumes:
      - "./:/opt/app"

  #################################################################
  # OFFICIAL MYSQL 8.0.40 SERVICE
  #################################################################
  mysql:
    image: percona/percona-server:8.0.40
    container_name: mysql
    networks:
      - tripwire
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD # do not use quotes
      - MYSQL_DATABASE=tripwire_database
      - MYSQL_USER=$MYSQL_USER # do not use quotes
      - MYSQL_PASSWORD=$MYSQL_PASSWORD # do not use quotes
    volumes:
      - mysql-data:/var/lib/mysql

  #################################################################
  # ADMINER SERVICE (DB web UI)
  #################################################################
  adminer:
    container_name: adminer
    image: adminer
    networks:
      - tripwire
    ports:
      - 9000:8080

  #################################################################
  # DB-SEED SERVICE
  #################################################################
  db-seed:
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
    container_name: db-seed
    depends_on:
      - mysql
    networks:
      - tripwire
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_ROOT_USER=root
      - DB_ROOT_PASS=$MYSQL_ROOT_PASSWORD
      - TRIPWIRE_DB=tripwire_database
      - SDE_DB=eve_dump
    # No need for volumes or ports
    # The seed script will run once, then exit

volumes:
  mysql-data:

networks:
  web:
  tripwire:

