		<link rel="stylesheet" href="css/donation-panel.css" />
		<div id="donate-panel">

			<p>Donate in game ISK/PLEX to  <a href="https://evewho.com/character/172043007" href="" target="_blank">Devlin Shardo</a> in game if you're feeling the love <3 <br />
			Donate real money to pay for server hosting for PC's Tripwire?  <a href="https://paypal.me/sutima?country.x=SE&locale.x=en_US">Paypal</a>
				<br /></p>
				<br />
				<form action="https://www.paypal.com/donate" method="post" target="_top">
					<input type="hidden" name="hosted_button_id" value="7F4RSNHNVZ69Y" />
					<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
					<img alt="" border="0" src="https://www.paypal.com/en_SE/i/scr/pixel.gif" width="1" height="1" />
					</form>

		</div>
